alias gs="git status"
alias gc="git commit -m"
alias gf="git fetch --prune origin"
alias gF="git fetch --prune --all"
alias gp="git pull origin"
alias gP="git push -u origin"
alias gR="git reset HEAD --hard"
alias gC="git clean -i"
