[general]
import = ["~/.config/alacritty/colors.toml", "~/.config/alacritty/os.toml"]
live_config_reload = true

[window]
dimensions = { columns = 0, lines = 0 }
position = "None"
padding = { x = 5, y = 0 }
dynamic_padding = false
decorations = "Full"
opacity = 1.0
blur = false
startup_mode = "Windowed"
dynamic_title = true
decorations_theme_variant = "None"
resize_increments = false
option_as_alt = "OnlyLeft"

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "IosevkaTerm Nerd Font Mono", style = "Regular" }
bold = { family = "IosevkaTerm Nerd Font Mono", style = "Bold" }
italic = { family = "IosevkaTerm Nerd Font Mono", style = "Italic" }
bold_italic = { family = "IosevkaTerm Nerd Font Mono", style = "Bold Italic" }
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }
builtin_box_drawing = true

[mouse]
hide_when_typing = true
