[font]
size = 16

[keyboard]
bindings = [
  { key = "C", mods = "Command", action = "Copy" },
  { key = "ะก", mods = "Command", action = "Copy" },
  { key = "ะ", mods = "Command", action = "Paste" },
  { key = "V", mods = "Command", action = "Paste" },
  { key = "A", mods = "Command", chars = "\u0002"},
  { key = "Left",  mods = "Option", chars = "\u001bb" },
  { key = "Right", mods = "Option", chars = "\u001bf" },
  { key = "Left", mods = "Command", chars = "\u0001" },
  { key = "Right", mods = "Command", chars = "\u0005" },
  { key = "Backspace", mods = "Command", chars = "\u0015"},
  { key = "Backspace", mods = "Option", chars = "\u0017"}
]
