[keyboard]
bindings = [
  { key = "A", mods = "Command", chars = "\u0002"},
  { key = "Left",  mods = "Option", chars = "\u001bb" },
  { key = "Right", mods = "Option", chars = "\u001bf" },
  { key = "Left", mods = "Command", chars = "\u0001" },
  { key = "Right", mods = "Command", chars = "\u0005" },
  { key = "Backspace", mods = "Command", chars = "\u0015"},
  { key = "Backspace", mods = "Option", chars = "\u0017"}
]
