#Font
font_family      Iosevka Term
bold_font        Iosevka Term Bold
italic_font      Iosevka Term Italic
bold_italic_font Iosevka Term Bold Italic
font_size 15.0
disable_ligatures always

# All symbols in NF (https://github.com/ryanoasis/nerd-fonts/wiki/Glyph-Sets-and-Code-Points)
symbol_map U+23FB-U+23FE,U+2665,U+26A1,U+F400-U+F532,U+2B58,U+E000-U+E00A,U+E0A0-U+E0A2,U+E0A3,U+E0B0-U+E0B3,U+E0B4-U+E0C8,U+E0CA,U+E0CC-U+E0D4 IosevkaTerm Nerd Font Mono
symbol_map U+E200-U+E2A9,U+E300-U+E3E3,U+E5FA-U+E6B1,U+E700-U+E7C5,U+EA60-U+EBEB,U+F000-U+F2E0,U+F300-U+F372,U+F400U+F532,U+F500-U+FD46,U+F0001-U+F1AF0 IosevkaTerm Nerd Font Mono
narrow_symbols U+23FB-U+23FE,U+2665,U+26A1,U+F400-U+F532,U+2B58,U+E000-U+E00A,U+E0A0-U+E0A2,U+E0A3,U+E0B0-U+E0B3,U+E0B4-U+E0C8,U+E0CA,U+E0CC-U+E0D4 1
narrow_symbols +E200-U+E2A9,U+E300-U+E3E3,U+E5FA-U+E6B1,U+E700-U+E7C5,U+EA60-U+EBEB,U+F000-U+F2E0,U+F300-U+F372,U+F400U+F532,U+F500-U+FD46,U+F0001-U+F1AF0 1

cursor_shape block

scrollback_lines 10000
shell_integration no-cursor
mouse_hide_wait 1.0
confirm_os_window_close -1

#Tab Bar
tab_bar_edge top
tab_bar_align center
tab_bar_min_tabs 2
tab_bar_margin_width 0.0
tab_bar_margin_height 0.0 0.0
tab_bar_style slant
tab_title_template "    {index}    "
active_tab_font_style bold
inactive_tab_font_style bold

term xterm-256color
enabled_layouts splits:split_axis=horizontal,stack

#Colors
include colors.conf

#OS specific configs
include os.conf
