#Keyboard shortcuts
map alt+right next_tab
map alt+left previous_tab
map ctrl+t new_tab
map ctrl+w close_tab
map ctrl+c copy_or_interrupt
map ctrl+v paste_from_clipboard
map alt+shift+right move_tab_forward
map alt+shift+left move_tab_backward
map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5
map alt+6 goto_tab 6
map alt+7 goto_tab 7
map alt+8 goto_tab 8
map alt+9 goto_tab 9
map ctrl+shift+d new_window
map ctrl+shift+w close_window
map ctrl+alt+right next_window
map ctrl+alt+left previous_window
map ctrl+shift+alt+right move_window_forward
map ctrl+shift+alt+left move_window_backward

