macos_show_window_title_in window

#Keyboard shortcuts
map cmd+right next_tab
map cmd+left previous_tab
map cmd+t new_tab
map cmd+w close_tab
map cmd+shift+right move_tab_forward
map cmd+shift+left move_tab_backward
map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5
map cmd+6 goto_tab 6
map cmd+7 goto_tab 7
map cmd+8 goto_tab 8
map cmd+9 goto_tab 9

map cmd+d launch --location=vsplit
map cmd+shift+d launch --location=hsplit

map cmd+shift+h neighboring_window left
map cmd+shift+j neighboring_window down
map cmd+shift+k neighboring_window up
map cmd+shift+l neighboring_window right

map cmd+option+h move_window left
map cmd+option+j move_window down
map cmd+option+k move_window up
map cmd+option+l move_window right

map ctrl+shift+h resize_window wider
map ctrl+shift+j resize_window shorter
map ctrl+shift+k resize_window taller
map ctrl+shift+l resize_window narrower
map ctrl+shift+r resize_window reset

map cmd+f toggle_layout stack

map cmd+shift+w close_window_with_confirmation
map cmd+w close_tab
