unbind r
bind r source-file ~/.tmux.conf
set -g mouse on
set -g default-terminal "alacritty"
#set -g default-terminal "screen-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -sg escape-time 10
set -g focus-events on
set -g history-limit 5000
set -g base-index 1
set -g pane-base-index 1

#Key binding
unbind t
bind t new-window

unbind w
bind w kill-window

unbind j
bind j select-pane -D

unbind k
bind k select-pane -U

unbind h
bind h select-pane -L

unbind l
bind l select-pane -R

unbind <
bind < swap-window -d -t -1

unbind >
bind > swap-window -d -t +1

#Catppuccin Frappe
thm_rosewater="#f2d5cf"
thm_flamingo="#eebebe"
thm_pink="#f4b8e4"
thm_mauve="#ca9ee6"
thm_red="#e78284"
thm_maroon="#ea999c"
thm_peach="#ef9f76"
thm_yellow="#e5c890"
thm_green="#a6d189"
thm_teal="#81c8be"
thm_sky="#99d1db"
thm_sapphire="#85c1dc"
thm_blue="#8caaee"
thm_lavender="#babbf1"
thm_text="#c6d0f5"
thm_subtext1="#b5bfe2"
thm_subtext0="#a5adce"
thm_overlay2="#949cbb"
thm_overlay1="#838ba7"
thm_overlay0="#737994"
thm_surface2="#626880"
thm_surface1="#51576d"
thm_surface0="#414559"
thm_base="#303446"
thm_mantle="#292c3c"
thm_crust="#232634"

#Status bar settings
set -g status-position top
set -g status-justify right

#Default status bar colors
set -g status-style fg=$thm_text,bold,bg=$thm_crust

#Unactive tab
set -g window-status-style fg=$thm_overlay0,bg=$thm_mantle
set -g window-status-format ' #I #W '

#Active tab
set -g window-status-current-style fg=$thm_text,bg=$thm_base
set -g window-status-current-format '  #I #W '

#Panels
set -g status-right ""
set -g status-left "  #S "
set -g status-left-style fg=$thm_text,bg=$thm_base
