#!/bin/sh

TMUX_SESSION=$1
PROJECT_DIRECTORY=$2

if [ -n "$TMUX" ]; then
	echo "You must detach from current tmux session."
	exit
fi

if [ -z "$TMUX_SESSION" ]; then
	echo "The tmux session is not specified."
	exit
fi

if [ -d "$PROJECT_DIRECTORY" ]; then
	cd $PROJECT_DIRECTORY
fi

FIND_SESSION="$(tmux ls | grep $TMUX_SESSION)"
if [[ -z $FIND_SESSION || "$FIND_SESSION" == "" ]]; then
	echo "Creating tmux session."

	tmux new-session -d -s $TMUX_SESSION

	tmux select-window -t $TMUX_SESSION:1
	tmux send-keys nvim Enter

	tmux new-window -t $TMUX_SESSION:2
	tmux select-window -t $TMUX_SESSION:2
	tmux split-window -v

	tmux select-window -t $TMUX_SESSION:1
fi

tmux attach-session -t $TMUX_SESSION
