import = ["~/.config/alacritty/colors.toml", "~/.config/alacritty/os.toml"]
live_config_reload = true

[font.normal]
family = "Iosevka Nerd Font Mono"

[font.bold]
family = "Iosevka Nerd Font Mono"

[font.italic]
family = "Iosevka Nerd Font Mono"

[font.bold_italic]
family = "Iosevka Nerd Font Mono"

[font]
size = 16

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "Full"
dynamic_padding = true
dynamic_title = false
startup_mode = "Windowed"
decorations_theme_variant = "Dark"
