[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002"
key = "A"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002s"
key = "S"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002t"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002w"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00021"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00022"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00023"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00024"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00025"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00026"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00027"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00028"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00029"
key = "Key9"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002p"
key = "LBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002n"
key = "RBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002<"
key = "LBracket"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002>"
key = "RBracket"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002%"
key = "D"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002\""
key = "D"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002W"
key = "W"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002h"
key = "H"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002j"
key = "J"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002k"
key = "K"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002l"
key = "L"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002H"
key = "H"
mods = "Command|Option|Shift"

[[keyboard.bindings]]
chars = "\u0002J"
key = "J"
mods = "Command|Option|Shift"

[[keyboard.bindings]]
chars = "\u0002K"
key = "K"
mods = "Command|Option|Shift"

[[keyboard.bindings]]
chars = "\u0002L"
key = "L"
mods = "Command|Option|Shift"

[[keyboard.bindings]]
chars = "\u0002z"
key = "F"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002{"
key = "Comma"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002}"
key = "Period"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002["
key = "V"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0001"
key = "Left"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0005"
key = "Right"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Option"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Option"
