DEFAULT_USER="$(whoami)"

EDITOR=nvim

DOTFILES_HOME=$HOME/.config/dotfiles

autoload -U colors && colors
setopt PROMPT_SUBST
source $DOTFILES_HOME/zsh/themes/default.zsh-theme

HISTFILE=$HOME/.zhistory
SAVEHIST=1000
HISTSIZE=999
setopt share_history
setopt hist_expire_dups_first
setopt hist_ignore_dups
setopt hist_verify

function lfcd () {
	tmp="$(mktemp)"
	lf -last-dir-path="$tmp" "$@"
	if [ -f "$tmp" ]; then
		dir="$(cat "$tmp")"
		rm -f "$tmp"
		if [ -d "$dir" ]; then
			if [ "$dir" != "$(pwd)" ]; then
				cd "$dir"
			fi
		fi
	fi
}

alias t="tmux new -ADs main"
alias v="nvim"
alias lf="lfcd"
alias lg="lazygit"
alias n="tput bel"

function zvm_config() {
	ZVM_VI_HIGHLIGHT_BACKGROUND=#51576d
	ZVM_VI_HIGHLIGHT_FOREGROUND=#c6d0f5
	ZVM_VI_HIGHLIGHT_EXTRASTYLE=bold
}

function zvm_after_lazy_keybindings() {
	zvm_bindkey vicmd 'J' history-search-forward
	zvm_bindkey vicmd 'K' history-search-backward
}

if [[ "$(uname 2>/dev/null)" = "Darwin" ]]; then
	source $DOTFILES_HOME/zsh/macos.zsh
fi

autoload -Uz compinit

zstyle ':completion:*' menu select

compinit
