export EDITOR=nvim
export DEFAULT_USER="$(whoami)"

export DOTFILES_HOME=$HOME/.config/dotfiles

autoload -U colors && colors
setopt PROMPT_SUBST
source $DOTFILES_HOME/zsh/themes/default.zsh-theme

export CLICOLOR=1
export LSCOLORS=ExGxBxDxCxAgAdXbAgAcAd
export LS_COLORS="di=1;34:ln=1;36:so=1;31:pi=1;33:ex=1;32:bd=1;30;46:cd=1;30;43:su=1;0;41:sg=1;30;46:tw=1;30;42:ow=1;30;43"

HISTFILE=$HOME/.zsh_history
SAVEHIST=10000
HISTSIZE=10000

setopt inc_append_history
setopt extended_history
setopt hist_expire_dups_first
setopt hist_ignore_all_dups
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_verify
setopt share_history

if [ "$(uname 2>/dev/null)" = "Darwin" ]; then
	source $DOTFILES_HOME/zsh/core/macos.zsh
fi

if [ "$(uname 2>/dev/null)" = "Linux" ]; then
	source $DOTFILES_HOME/zsh/core/linux.zsh
fi

if [ -n "$(brew --prefix 2>/dev/null)" ]; then
	source $DOTFILES_HOME/zsh/core/brew.zsh
fi

export PATH=$DOTFILES_HOME/tmux/layouts:$PATH

alias icat="wezterm imgcat"
alias t="tmux new -ADs main"
alias v="nvim"
alias lg="lazygit"
alias ez="eza --colour=always --time-style='+%d.%m.%Y %H:%M'"
alias ea="ez -la"
alias eg="ea --git"
alias egt="eg --tree --ignore-glob .git"
alias ls="ls --color=auto"
alias la="ls -lah --color=auto"
alias grep='grep --color=auto'

autoload -Uz compinit

eval "$(zoxide init zsh)"

zstyle ':completion:*' menu select
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"

bindkey '^I' menu-complete
bindkey '^[[Z' reverse-menu-complete
bindkey '^[[1;2B' history-beginning-search-forward
bindkey '^[[1;2A' history-beginning-search-backward
bindkey '^[b' backward-word
bindkey '^[f' forward-word
bindkey '^a' beginning-of-line
bindkey '^e' end-of-line
bindkey '^U' backward-kill-line
